version: "3.8"
services:
  backend:
    build: .
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - frontend
  frontend:
    build: .
    command: streamlit run frontend/main.py --server.port 8501
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
